require("install.lazy")

require("plugins.lazy")
require("plugins.nvim-cmp")
require("plugins.telescope")
require("plugins.conform")
require("plugins.treesitter")
require("plugins.dashboard")
require("mason-lspconfig")
require("plugins.nvim-highlights")
require("plugins.neotree")
require("plugins.gitsigns")
require("plugins.autopairs")
require("plugins.indent")
-- require("plugins.supermaven")

require("core.options")
require("core.keymaps")
