shell /bin/zsh

# === Font Settings ===
font_family      JetBrainsMono Nerd Font Mono
bold_font        JetBrainsMono Nerd Font Mono Bold
italic_font      JetBrainsMono Nerd Font Mono Italic
bold_italic_font JetBrainsMono Nerd Font Mono Bold Italic
font_size        16.0

# === Terminal Behavior ===
term xterm-kitty
scrollback_pager_history_size 1000000

# === Cursor Behavior ===
cursor_shape block
cursor_blink_interval -1
cursor_stop_blinking_after 3
hide_cursor_when_typing no
cursor_blink_on_focus yes
inactive_cursor_shape hollow

# === Window Settings ===
hide_window_decorations yes
window_padding_width 3 3 0 0

# Alternatively, force fullscreen
remember_window_size no
initial_window_width 1920
initial_window_height 1080

# === Colorscheme Import ===
include ~/.config/kitty/themes/tokyonight.conf

# === Background ===
#background_image /home/x/Pictures/Wallpapers/bv.png
#background_image_layout scaled
background_opacity .95
#background_blue 0.0
#background_tint 0.8
